### PR TITLE
remove compilation errors from julia cheatsheet

### PR DESCRIPTION
**Pull request by natashawatkins**
- gets rid of a couple of the compilation errors stemming from code blocks incorrectly formatted in julia cheatsheet

### CODE REVIEW

**Comment by mmcky** [comment]
Hi @natashawatkins. The diff shows a big difference at the end of file which I presume is your editor. It looks the same. Are you confident in these changes? If so I will merge.

**Comment by natashawatkins** [comment]
I'm not where the compilation errors I was seeing went :\ ignore this for now because they're not appearing on the master branch

There was an error though in index.rst which I've fixed in #44

**Comment by mmcky** [comment]
can you run ``make clean`` and then ``make html``. I think the errors will return. Sphinx hides some error types after the initial run sometimes.

**Comment by natashawatkins** [comment]
Did that and the error is still gone.

The error was
`/Users/natashawatkins/Dropbox/QuantEcon/QuantEcon.cheatsheet/index.rst:28: WARNING: Explicit markup ends without a blank line; unexpected unindent.`

**Comment by mmcky** [comment]
Ok -- I will close this PR (without merge) then?

**Comment by natashawatkins** [comment]
Yep that's fine, but there is still an index.rst which i'll fix in #44

**Pull request closed without merging**
