### PR TITLE
Adding QE menubar and new header style

### PR DESCRIPTION
**Pull request by DrDrij**
- Adding QE menubar
- "Cheatsheet" removed from nav menu items
- New "pill" nav menu style
- New logo
- Added "Cheatsheets by QuantEcon" as site title

### CODE REVIEW

**Comment by natashawatkins** [comment]
@DrDrij for some reason the new pages seem to have lost the css

image

**Comment by DrDrij** [comment]
make clean, then make html

**Comment by DrDrij** [comment]
The css files have been moved into a css directory. Let me know if that helps?

**Comment by natashawatkins** [comment]
I'm still getting the same issue, even after running `make clean`

**Comment by mmcky** [comment]
@natashawatkins have you refreshed your browser?

**Comment by mmcky** [comment]
@DrDrij this is looking nice on my machine.

**Comment by natashawatkins** [comment]
@mmcky Yep I still get this even after doing a full refresh. I got it on both linux and mac.

`make preview` works though! Looks good to me - I'd just prefer a more subtle yellow for the lightbulb if you could switch that over @DrDrij :)

**Comment by mmcky** [comment]
Ahh -- perhaps you weren't viewing the html via a web server (i.e. python -m http.server)?

**Comment by DrDrij** [comment]
@natashawatkins @mmcky This one should be ready to merge and push to live?

**Comment by natashawatkins** [comment]
Yep I like it

**Pull request merged**
