### PR TITLE
A few typos with arrays?

### PR DESCRIPTION
**Pull request by jlperla**

### CODE REVIEW

**Comment by arnavs** [comment]
For the first one, shouldn't we remove the left paren instead of adding a right one? So, `np.array([some, array, of, numbers])` instead of `np.array(([some, array, ...]))`.

**Comment by jlperla** [comment]
Don't know.... but something is wrong with it.

**Comment by arnavs** [comment]
OK. Just tried it with the one paren on each side and it checks out, so I'll do that instead (the double might confuse people). 

@natashawatkins, after this is merged in, could you take care of populating the cheatsheets on the live site?

**Comment by arnavs** [comment]
Done, thanks @jlperla

**Pull request merged**
