### PR TITLE
Undeprecate the pure Julia cheatsheet and add version info, anonymous functions

### PR DESCRIPTION
**Pull request by arnavs**
See also https://github.com/QuantEcon/QuantEcon.cheatsheet/issues/52.

### CODE REVIEW

**Comment by mmcky** [comment]
hey @arnavs happy for this to be merged? Have you confirmed it builds?

**Comment by arnavs** [comment]
Hey @mmcky I forgot that my draft changes to the main cheatsheet would be upstreamed to this PR. Let me parcel those out and then this should be ready.

**Comment by arnavs** [comment]
@mmcky OK, whenever you have time, could you take a look at why the syntax is awry here? It renders fine in an editor, and builds, but the LaTeX is just wrong. Would help us iterate on the main MATLAB-Julia-Python cheatsheet.

**Comment by arnavs** [comment]
@mmcky apparently the issue only applies to the PDF (which isn't used) and not the published HTML. so this should be usable for the launch if need be. 

cc @natashawatkins

**Comment by natashawatkins** [comment]
Made a small change but looks good to merge now

**Comment by arnavs** [comment]
Closing this since it's covered by the other, open PR.

**Pull request closed without merging**
