### PR TITLE
add Julia 1.0 and python/matlab equivalents to main cheatsheet

### PR DESCRIPTION
**Pull request by natashawatkins**
I'm not sure if this PR will work

### CODE REVIEW

**Comment by natashawatkins** [comment]
Here's the package to do RST tables in sublime: https://github.com/vkocubinsky/SublimeTableEditor

You need to enable the editor on view and select keep left space and Pandoc style

**Comment by natashawatkins** [comment]
Hi @arnavs do you want to check the julia and main cheatsheet now? I've fixed issues in both.

**Comment by natashawatkins** [comment]
I added a python sparse matrix but it isn't all that neat....

**Comment by arnavs** [comment]
Thanks so much @natashawatkins for sorting this out. Looks great to me. And no worries about the sparse matrices in `scipy`, I think they aren't super clean anyways.

**Comment by jlperla** [comment]
A few tweaks here:
* In https://github.com/QuantEcon/QuantEcon.cheatsheet/blob/f1d1a6f76fb7f71e59cacafcb9a93e18821eb995/index.rst#sum--max--min  I think the `cumsum`, `maximum`, etc. requite the `dims` argument now.  I would run through all of them
* I think the `eigen` in Julia is wrong.

Eventually we will want to add better iteration examples.

**Comment by arnavs** [comment]
Good catch re the `dims = n`, didn't get to filling those all in. 

Edit: `eigen` is the right function, but the example has a typo. Will need branch access to fix.

**Comment by arnavs** [comment]
OK, I gave this another review, ran through the Julia code, and made some final tweaks.

**Pull request merged**
