### PR TITLE
Fix index compilation

### PR DESCRIPTION
**Pull request by natashawatkins**
- add in spaces after code blocks in table 1 to fix compilation errors

### CODE REVIEW

**Comment by natashawatkins** [comment]
argh, it kept my old commits @mmcky

**Comment by mmcky** [comment]
is this ready for review or you want to get your old commits out of this PR?

**Comment by mmcky** [comment]
can you also add a hidden toc object into index.rst so that we don't get the document missing warning?

**Comment by natashawatkins** [comment]
@mmcky Hi matt, ok sorry I messed that up because I accidentally made commits from #42 to my master, so I couldn't find the original compilation errors from julia-cheatsheet.rst

There are errors in both julia-cheatsheet.rst and index.rst that are fixed in this PR

I also added a hidden toctree

The only remaining errors are from intentional errors in the python cheatsheet

Feel free to test it out first :)

**Comment by mmcky** [comment]
Thanks @natashawatkins. This is great.

Why are these intentional?

```
/home/mmcky/repos-collab/QuantEcon.cheatsheet/index.rst:197: WARNING: Could not lex literal_block as "python". Highlighting skipped.                                                                                                          
/home/mmcky/repos-collab/QuantEcon.cheatsheet/index.rst:201: WARNING: Could not lex literal_block as "python". Highlighting skipped.
/home/mmcky/repos-collab/QuantEcon.cheatsheet/python-cheatsheet.rst:27: WARNING: Could not lex literal_block as "python". Highlighting skipped.
```

**Comment by natashawatkins** [comment]
For example
screen shot 2017-05-31 at 2 05 34 pm

Not really sure how we can suppress the error...

**Comment by mmcky** [comment]
the python issues were becuase of ``@`` requiring ``python3`` highlighter.

**Comment by mmcky** [comment]
we should have error/warning free compilation :)

**Comment by natashawatkins** [comment]
Ah yep that worked! Awesome

**Comment by mmcky** [comment]
Thanks @natashawatkins. I'll merge now.

**Pull request merged**
